# Generated by Django 4.2.4 on 2024-02-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('total_expected_duration', models.DurationField()),
                ('cost_of_construction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_of_building', models.ImageField(upload_to='projects/buildings/')),
                ('image_of_map', models.ImageField(upload_to='projects/maps/')),
                ('square_feet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engineer_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='my_app.company')),
            ],
        ),
    ]
