# Generated by Django 5.0.2 on 2024-02-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_image_remove_company_name_company_address_and_more'),
    ]

    operations = [
    ]
