# Generated by Django 5.0.2 on 2024-02-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20240213_1054'),
    ]

    operations = [
    ]
