# Generated by Django 5.0.2 on 2024-02-13 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20240213_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['start_date'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='my_app.professional'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost_of_construction',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='engineer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_of_building',
            field=models.ImageField(blank=True, null=True, upload_to='projects/buildings/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_of_map',
            field=models.ImageField(blank=True, null=True, upload_to='projects/maps/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_expected_duration',
            field=models.DurationField(help_text='Expected duration in days.'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
