# Generated by Django 5.0.2 on 2024-02-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_remove_project_company_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
