# Generated by Django 4.2.4 on 2024-02-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_project_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout1000to1500',
            fields=[
                ('layout_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('num_rooms', models.IntegerField()),
                ('num_halls', models.IntegerField()),
                ('num_kitchens', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_storeys', models.IntegerField()),
                ('layout_image', models.ImageField(upload_to='layouts/1000to1500/')),
                ('design_image', models.ImageField(upload_to='designs/1000to1500/')),
                ('sqr_ft', models.IntegerField(default=1001)),
            ],
            options={
                'verbose_name': 'Layout 1000-1500 sq ft',
                'verbose_name_plural': 'Layouts 1000-1500 sq ft',
            },
        ),
        migrations.CreateModel(
            name='Layout1500to2000',
            fields=[
                ('layout_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('num_rooms', models.IntegerField()),
                ('num_halls', models.IntegerField()),
                ('num_kitchens', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_storeys', models.IntegerField()),
                ('layout_image', models.ImageField(upload_to='layouts/1500to2000/')),
                ('design_image', models.ImageField(upload_to='designs/1500to2000/')),
                ('sqr_ft', models.IntegerField(default=1501)),
            ],
            options={
                'verbose_name': 'Layout 1500-2000 sq ft',
                'verbose_name_plural': 'Layouts 1500-2000 sq ft',
            },
        ),
        migrations.CreateModel(
            name='Layout500to1000',
            fields=[
                ('layout_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('num_rooms', models.IntegerField()),
                ('num_halls', models.IntegerField()),
                ('num_kitchens', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_storeys', models.IntegerField()),
                ('layout_image', models.ImageField(upload_to='layouts/500to1000/')),
                ('design_image', models.ImageField(upload_to='designs/500to1000/')),
                ('sqr_ft', models.IntegerField(default=500)),
            ],
            options={
                'verbose_name': 'Layout 500-1000 sq ft',
                'verbose_name_plural': 'Layouts 500-1000 sq ft',
            },
        ),
    ]
